[package]
name = "rbp-servicebus-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
rbp-serialization = { workspace = true, features = ["serialization-json"] }
